services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env.example
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "user_management" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    ports:
      - "5436:5432"
    networks:
      - app-network

  user_management:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - app-network
    env_file: .env.example
    entrypoint: "/entrypoint.sh"

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
