services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env.example
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "user_management" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    ports:
      - "5436:5432"
    networks:
      - app-network

  user_management:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - app-network
    env_file: .env.example
    entrypoint: "/entrypoint.sh"

  localstack:
    container_name: "localstack"
    image: localstack/localstack:4.0.3
    environment:
      - SERVICES=ses
    ports:
      - "4566:4566"
    env_file:
      - .env.example
    networks:
      - app-network
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data:
  localstack_data:

networks:
  app-network:
    driver: bridge
