"""empty message

Revision ID: 65b124ed3f8b
Revises: 26f0dc6d3150
Create Date: 2025-02-24 18:27:46.103261

"""

from typing import Union, Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65b124ed3f8b"
down_revision: Union[str, None] = "26f0dc6d3150"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
